const WIDTH_VALUE_AVATAR = '35';
const HEIGHT_VALUE_AVATAR = '35';
const REGULAR_EXPRESSION_SPACE = /\s/;
const REGULAR_EXPRESSION_HASHTAG = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;
const MAX_COUNT_HASHTAGS = 5;
const START_ARRAY_COMMENT = 0;
const END_ARRAY_COMMENT = 5;
const SCALE_STEP = 25;
const DECIMAL_SYSTEM = 10;
const DIVISION_ONE_HUNDRED = 100;
const MAX_PERCENTAGE_VALUE = 100;
const MIN_PERCENTAGE_VALUE = 25;
const MESSAGE_SHOW_TIME = 10000;
const URL_MINIATURES = 'https://25.javascript.pages.academy/kekstagram/data';
const URL_SUBMIT_FORM = 'https://25.javascript.pages.academy/kekstagram';
const ACTIVE_FILTER_BUTTON = 'img-filters__button--active';
const RERENDER_DELAY = 500;

export{WIDTH_VALUE_AVATAR, HEIGHT_VALUE_AVATAR, REGULAR_EXPRESSION_SPACE, REGULAR_EXPRESSION_HASHTAG, MAX_COUNT_HASHTAGS, START_ARRAY_COMMENT, END_ARRAY_COMMENT, SCALE_STEP, DECIMAL_SYSTEM, DIVISION_ONE_HUNDRED, MAX_PERCENTAGE_VALUE, MIN_PERCENTAGE_VALUE, MESSAGE_SHOW_TIME, URL_MINIATURES, URL_SUBMIT_FORM, ACTIVE_FILTER_BUTTON, RERENDER_DELAY};
