const NUMBER_OBJECTS = 25;
const NUMBER_COMMENTS = 5;
const INITIAL_VALUE_AVATAR = 1;
const END_VALUE_AVATAR = 6;
const INITIAL_VALUE_LIKES = 15;
const END_VALUE_LIKES = 200;
const WIDTH_VALUE_AVATAR = '35';
const HEIGHT_VALUE_AVATAR = '35';
const REGULAR_EXPRESSION_SPACE = /\s/;
const REGULAR_EXPRESSION_HASHTAG = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;
const MAX_COUNT_HASHTAGS = 5;

export{NUMBER_OBJECTS, NUMBER_COMMENTS, INITIAL_VALUE_AVATAR, END_VALUE_AVATAR, INITIAL_VALUE_LIKES,END_VALUE_LIKES, WIDTH_VALUE_AVATAR, HEIGHT_VALUE_AVATAR, REGULAR_EXPRESSION_SPACE, REGULAR_EXPRESSION_HASHTAG, MAX_COUNT_HASHTAGS};
